### ISSUE TITLE
Can you explain to me

### ISSUE THREAD

**Issue by sleeplessme** [lytemar/Applied-Data-Science-with-Python-University-of-Michigan#1]
hi, can you explain to me what are you doing in function to find good generalization overfitting and underfitting in applied python in machine learning? thank you

**Comment by lytemar** [comment]
I use cross-validation to find the optimal lambda that regularizes the fit in either LASSO or ridge regression.  This provides good protection against overfitting and underfitting.

**Comment by sleeplessme** [comment]
Sorry i still dont get it, i mean in this code
` for deg, data in enumerate(zip(r2_train, r2_test)):
        if data[0] < r2_train_sorted[5] and data[1] < r2_test_sorted[5]:
            Underfitting = deg
        if data[0] >= r2_train_sorted[5] and data[1] < r2_test_sorted[5]:
            Overfitting = deg
        if data[0] >= r2_train_sorted[5] and data[1] >= r2_test_sorted[7]:
            Good_Generalization = deg`
